### PR TITLE
Ability to retrieve scarab pricing for betrayal league

### PR DESCRIPTION
**Pull request by damianpoole**
Quick tweak based on this issue in Xenontrade - https://github.com/klayveR/xenontrade/issues/31

### CODE REVIEW

**Comment by klayver** [comment]
Thanks! I don't think the extra condition to check whether the league is Betrayal is necessary though, because poe.ninja also supports scarabs for default leagues (will be important once the league items and scarabs merge to Standard).

**Comment by damianpoole** [comment]
OK, I wasn't sure if they were going to be going into standard and didn't realise POE ninja already supports them 😄

**Comment by damianpoole** [comment]
I wanted to add tests around this but didn't want to impose my test suite preference on you 😉 If I was to create a PR with test coverage, which suite are you most familiar with?

**Comment by klayver** [comment]
Tests would be lovely! I'm still fairly new to Node and I haven't worked with any testing solution for it yet. I've been looking at Jest and would like to try it out at some point, are you familiar with that? Which one do you prefer?

**Comment by damianpoole** [comment]
I'm probably the most familiar with Jest. I'll update the PR with using Jest then 👍

**Comment by damianpoole** [comment]
I'm happy for this to be merged and I will then start looking at adding further tests. Don't like bloating out a PR 😉 😸

**Pull request merged**
